package com.infineon.cv;

import org.eclipse.cdt.core.IMarkerGenerator;
import org.eclipse.cdt.core.errorparsers.AbstractErrorParser;
import org.eclipse.cdt.core.errorparsers.ErrorPattern;

/**
 * The ARM error parser class. It parses the error generated by the compiler
 * 
 * @author gautier
 */
public class ARMErrorParser extends AbstractErrorParser {

	private static final ErrorPattern[] patterns = { 
		new ErrorPattern("\"(.+)\", line ([\\d]+): Error: (.*)", 1, 2, 3, 0, IMarkerGenerator.SEVERITY_ERROR_BUILD),
		new ErrorPattern("\"(.+)\", line ([\\d]+): Warning: (.*)", 1, 2, 3, 0, IMarkerGenerator.SEVERITY_WARNING),

	// new ErrorPattern(
	// "\"([a-zA-Z0-9_\\]+)\"(, line ) ([0-9]+) (: Error: ) (.*)", 1,
	// 2, 3, 0, IMarkerGenerator.SEVERITY_ERROR_RESOURCE),
	// new ErrorPattern(
	// "\"([a-zA-Z0-9_\\]+)\"(, line ) ([0-9]+) (: Warning: ) (.*)", 1,
	// 2, 3, 0, IMarkerGenerator.SEVERITY_WARNING),
	};

	/**
	 * Constructor to set the error pattern.
	 */
	public ARMErrorParser() {
		super(patterns);
	}
}
